TAG_MAP = {'$': {74: 99}, "''": {74: 97, 'PunctSide_fin': True, 'PunctType_quot': True},
           ',': {74: 97, 'PunctType_comm': True}, '-LRB-': {74: 97, 'PunctSide_ini': True, 'PunctType_brck': True},
           '-RRB-': {74: 97, 'PunctSide_fin': True, 'PunctType_brck': True}, '.': {74: 97, 'PunctType_peri': True},
           ':': {74: 97}, 'ADD': {74: 101}, 'AFX': {74: 84, 'Hyph_yes': True}, 'CC': {74: 89, 'ConjType_comp': True},
           'CD': {74: 93, 'NumType_card': True}, 'DT': {74: 90}, 'EX': {74: 95, 'AdvType_ex': True},
           'FW': {74: 101, 'Foreign_yes': True}, 'HYPH': {74: 97, 'PunctType_dash': True}, 'IN': {74: 85},
           'JJ': {74: 84, 'Degree_pos': True}, 'JJR': {74: 84, 'Degree_comp': True},
           'JJS': {74: 84, 'Degree_sup': True}, 'LS': {74: 101, 'NumType_ord': True},
           'MD': {74: 100, 'VerbType_mod': True}, 'NFP': {74: 97}, 'NN': {74: 92, 'Number_sing': True},
           'NNP': {74: 96, 'NounType_prop': True, 'Number_sing': True},
           'NNPS': {74: 96, 'NounType_prop': True, 'Number_plur': True}, 'NNS': {74: 92, 'Number_plur': True},
           'PDT': {74: 90}, 'POS': {74: 94, 'Poss_yes': True}, 'PRP': {74: 95, 'PronType_prs': True},
           'PRP$': {74: 90, 'Poss_yes': True, 'PronType_prs': True}, 'RB': {74: 86, 'Degree_pos': True},
           'RBR': {74: 86, 'Degree_comp': True}, 'RBS': {74: 86, 'Degree_sup': True},
           'RP': {74: 85}, 'SYM': {74: 99}, 'TO': {74: 94, 'PartType_inf': True, 'VerbForm_inf': True},
           'UH': {74: 91}, 'VB': {74: 100, 'VerbForm_inf': True},
           'VBD': {74: 100, 'Tense_past': True, 'VerbForm_fin': True},
           'VBG': {74: 100, 'Aspect_prog': True, 'Tense_pres': True, 'VerbForm_part': True},
           'VBN': {74: 100, 'Aspect_perf': True, 'Tense_past': True, 'VerbForm_part': True},
           'VBP': {74: 100, 'Tense_pres': True, 'VerbForm_fin': True},
           'VBZ': {74: 100, 'Number_sing': True, 'Person_three': True, 'Tense_pres': True, 'VerbForm_fin': True},
           'WDT': {74: 90}, 'WP': {74: 95}, 'WP$': {74: 90, 'Poss_yes': True},
           'WRB': {74: 86}, 'XX': {74: 101},
           '_SP': {74: 103}, '``': {74: 97, 'PunctSide_ini': True, 'PunctType_quot': True}}
